export const univData4 = { // 베트남 국제학교
	'4_1': {
		nameEn: "St Andrews International School Bangkok",
		nameKo: "세인트앤드류스 국제학교",
		desc: "St Andrews Bangkok은 방콕의 대표적인 영국계 국제학교 중 하나로, Nord Anglia Education 소속입니다. 유아부터 고등과정까지 운영하며, 영국 커리큘럼을 바탕으로 IGCSE와 IB Diploma까지 이어집니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1997년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "방콕",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제/커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, IB",
		item_tit_5: "재학생수",
		item_tit_desc_5: "약 2,000명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 THB 320,160 ~ 849,100 ※ 학년 및 프로그램에 따라 변동",

	},
	'4_2': {
		nameEn: "The American School of Bangkok",
		nameKo: "방콕 미국국제학교",
		desc: "The American School of Bangkok(ASB)은 방콕의 미국식 국제학교로, Sukhumvit와 Green Valley 두 캠퍼스를 운영합니다. 미국 커리큘럼 기반이며 AP, AP Capstone, 일부 캠퍼스에서는 IB Diploma 옵션도 제공합니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1983년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "방콕 ",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제/커리큘럼",
		item_tit_desc_4: "미국식 AP / IBDP",
		item_tit_5: "재학생수",
		item_tit_desc_5: "약 1,500명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 THB 453,450 ~ 808,630 ※ 학년 및 프로그램에 따라 변동",

	},
	'4_3': {
		nameEn: "NIST International School Bangkok",
		nameKo: "NIST 국제학교",
		desc: "NIST는 태국을 대표하는 국제학교 중 하나로, 비영리 PK-12 학교입니다. 1951년부터 운영되어 온 오랜 전통의 학교이며, 방콕권 국제학교 중 인지도가 매우 높습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1992년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "방콕 ",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제/커리큘럼",
		item_tit_desc_4: "Full IB (PYP/MYP/IBDP)",
		item_tit_5: "재학생수",
		item_tit_desc_5: "약 1,800명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 THB 640,000 ~ 1,162,000 ※ 학년 및 프로그램에 따라 변동",

	},
	'4_4': {
		nameEn: "International School Bangkok(ISB)",
		nameKo: "방콕 국제학교",
		desc: "ISB는 방콕 외곽에 위치한 태국 대표 IB 국제학교 중 하나입니다. 넓은 캠퍼스와 우수한 스포츠 및 시설을 갖춘 것이 특징입니다",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1951년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "방콕 ",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제/커리큘럼",
		item_tit_desc_4: "미국식 AP",
		item_tit_5: "재학생수",
		item_tit_desc_5: "약 1,800명 ",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 THB 440,100 ~ 944,600 ※ 학년 및 프로그램에 따라 변동",

	},
	'4_5': {
		nameEn: "PREM International School",
		nameKo: "프렘 인터내셔널 국제학교",
		desc: "PREM International School은 태국 북부 치앙마이에 위치한 프리미엄 국제학교입니다. 태국 최초의 4개 IB 프로그램 제공 학교로 소개되며, 데이스쿨과 보딩스쿨을 함께 운영합니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2001년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "치앙마이",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제/커리큘럼",
		item_tit_desc_4: "Full IB (PYP/MYP/IBDP)",
		item_tit_5: "재학생수",
		item_tit_desc_5: "약 600명 ",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 THB 440,100 ~ 944,600 (보딩 별도) ※ 학년 및 프로그램에 따라 변동",

	},
};