export const univData6 = { // 싱가포르 국립대
	'6_1': {
		nameEn: "National University of Singapore",
		nameKo: "싱가포르 국립 대학교",
		desc: "1905년 의과대학으로 출범하여 현재는 아시아 No.1 대학으로 인문, 상경, 과학 등 수많은 분야에서 최고수준의 연구중심 대학입니다. ",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1905년 ",
		item_tit_2: "재학생수",
		item_tit_desc_2: "40,000 명 이상",
		item_tit_3: "대학인지도",
		item_tit_desc_3: "전세계 8위",
		item_tit_4: "대표전공",
		item_tit_desc_4: "경영, 약학, 컴퓨터과학, 공학 등",
		item_tit_5: "평균 연학비",
		item_tit_desc_5: "일반 약 4000만원 / 국비지원 시 약 2500만원",
		item_tit_6: "입학조건",
		item_tit_desc_6: "약 20개 국가별 로컬전형 성적<br> IB, AP 스쿨 등 국제전형 성적<br> 한국 교과정 성적만으로 접수 불가",
	},
	'6_2': {
		nameEn: "Nanyang Technology University",
		nameKo: "난양공과 대학교",
		desc: "난양 공과 대학은 아시아 최고의 공학전공분야를 운영하고 있으며, 동시에 종합대학으로써 경영, 사회 인문학까지 폭넓은 전공을 운영하고 있습니다",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1991년",
		item_tit_2: "재학생수",
		item_tit_desc_2: "35,000 명 이상",
		item_tit_3: "대학인지도",
		item_tit_desc_3: "전세계 12위",
		item_tit_4: "대표전공",
		item_tit_desc_4: "항공우주공학, 로보틱스, 화학 및 생명공학, 경영 등",
		item_tit_5: "평균 연학비",
		item_tit_desc_5: "일반 약 3700만원(상경계 4600만원) / 국비지원 시 약 2500만원",
		item_tit_6: "입학조건",
		item_tit_desc_6: "약 20개 국가별 로컬전형 성적<br>IB, AP 스쿨 등 국제전형 성적<br>한국 교과정 성적만으로 접수가능(내신 또는 수능)",
	},
	'6_3': {
		nameEn: "Singapore Management University",
		nameKo: "싱가포르 경영 대학교",
		desc: "싱가포르 경영대학은 3대 국립대 중 하나로써 경영, 법, 컴퓨터 분야를 중심으로하는 연구중심 대학입니다. 특히 상경계열 분야에서 인지도가 높습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2000년",
		item_tit_2: "재학생수",
		item_tit_desc_2: "13,000 명 이상",
		item_tit_3: "대학인지도",
		item_tit_desc_3: "전세계 511위",
		item_tit_4: "대표전공",
		item_tit_desc_4: "경영, 회계, 법, 경제 등",
		item_tit_5: "평균 연학비",
		item_tit_desc_5: "일반 약 4800만원 / 국비지원 시 약 3000만원",
		item_tit_6: "입학조건",
		item_tit_desc_6: "약 20개 국가별 로컬성적을 기타전형으로 통합지원<br>IB, AP 스쿨 등 국제전형 성적<br>한국 교과정 성적만으로 접수가능(내신과 수능)",
	},
	'6_4': {
		nameEn: "Singapore University of Technology Design",
		nameKo: "싱가포르 기술디자인 대학교",
		desc: "싱가포르 기술디자인대학은 설립당시 MIT 대학과 파트너쉽관계로 기술과 디자인 융합전공프로그램을 개발하였고 현재 5개의 전공 프로그램을 운영하고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2000년",
		item_tit_2: "재학생수",
		item_tit_desc_2: "3,000 명 이상",
		item_tit_3: "대학인지도",
		item_tit_desc_3: "전세계 519위",
		item_tit_4: "대표전공",
		item_tit_desc_4: "건축, 인공지능, 시스템공학, 제품디자인 등",
		item_tit_5: "평균 연학비",
		item_tit_desc_5: "일반 약 6200만원 / 국비지원 시 약 3500만원",
		item_tit_6: "입학조건",
		item_tit_desc_6: "한국 교과정 포함 약 20개 국가별 로컬성적을 기타전형으로 통합지원 가능",
	},
	'6_5': {
		nameEn: "Singapore University of Social Science",
		nameKo: "싱가포르 사회과학 대학교",
		desc: "싱가포르 사회과학 대학은 경영학부, 인적자원개발학부, 인문행동과학학부, 기술과학 학부를 운영하고 있으며, 우수한 취업지원 프로그램을 운영하고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2017년",
		item_tit_2: "재학생수",
		item_tit_desc_2: "19,000 명 이상",
		item_tit_3: "대학인지도",
		item_tit_desc_3: "순위없음",
		item_tit_4: "대표전공",
		item_tit_desc_4: "회계, 경영분석, 금융, 인적자원관리, 유통물류 등",
		item_tit_5: "평균 연학비",
		item_tit_desc_5: "일반 약 4000만원 / 국비지원 시 약 2300만원",
		item_tit_6: "입학조건",
		item_tit_desc_6: "약 34개 국가별 로컬전형 성적<br>IB, AP 스쿨 등 국제전형 성적<br>한국 교과정 성적만으로 접수가능(내신 또는 수능)",
	},
};