export const univData5 = { // 태국 국제학교
	'5_1': {
		nameEn: "BIS HCMC (British International School Ho Chi Minh City)",
		nameKo: "호치민 영국 국제학교",
		desc: "BIS HCMC는 호치민의 대표적인 영국계 국제학교로, Nord Anglia Education 소속입니다. 유아부터 고등과정까지 운영하며, 영국식 교육과정 위에 IGCSE와 IB Diploma를 제공합니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1997년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "호치민",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제/커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "재학생수",
		item_tit_desc_5: "2,300명 이상",
		item_tit_6: "평균학비",
		item_tit_desc_6: "연간 VND 322,000,000 ~ 956,300,000 ※ 학년 및 프로그램에 따라 변동",
	},
	'5_2': {
		nameEn: "SSIS (Saigon South International School)",
		nameKo: "사이공 국제학교",
		desc: "SSIS는 호치민시 사이공 사우스에 위치한 미국식 국제학교입니다. 비영리 미국식 국제학교 (IB Diploma 제공)이며, 미국식 커리큘럼을 기반으로 한 학생 중심 교육을 강조합니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1997년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "호치민",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제/커리큘럼",
		item_tit_desc_4: "미국교육과정 AP / SAT",
		item_tit_5: "재학생수",
		item_tit_desc_5: "1,500명 이상",
		item_tit_6: "평균학비",
		item_tit_desc_6: "연간 VND 509,800,000 ~ 882,200,000 ※ 학년 및 프로그램에 따라 변동",
	},
	'5_3': {
		nameEn: "ISHCMC (International School Ho Chi Minh City)",
		nameKo: "호치민시티 국제학교",
		desc: "ISHCMC는 베트남 최초의 IB World School 중 하나로 알려진 학교입니다. 학생 중심의 혁신적인 교육 환경을 제공하며, 탐구 기반 학습을 통해 비판적 사고와 창의성을 키웁니다. 또한 다양한 국적의 학생들이 함께하는 글로벌 커뮤니티 속에서 국제적 감각과 협업 능력을 자연스럽게 함양할 수 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1993년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "호치민",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제/커리큘럼",
		item_tit_desc_4: "Full IB (PYP/MYP/IBDP)",
		item_tit_5: "재학생수",
		item_tit_desc_5: "1,500명 이상",
		item_tit_6: "평균학비",
		item_tit_desc_6: "연간 VND 330,000,000 ~ 1,000,000,000 ※ 학년 및 프로그램에 따라 변동",
	},
	'5_4': {
		nameEn: "UNIS Hanoi (United Nations International School of Hanoi)",
		nameKo: "하노이 유엔 국제학교",
		desc: "유엔(UN) 관련 기관 지원으로 설립된 비영리 국제학교 입니다. IB 전 과정(PYP·MYP·DP)을 운영하는 비영리 국제학교 입니다. ",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1988년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "하노이",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제/커리큘럼",
		item_tit_desc_4: "Full IB (PYP/MYP/IBDP)",
		item_tit_5: "재학생수",
		item_tit_desc_5: "1,100명 이상",
		item_tit_6: "평균학비",
		item_tit_desc_6: "연간 VND 331,000,000~1,007,000,000 ※ 학년 및 프로그램에 따라 변동",
	},
	'5_5': {
		nameEn: "Concordia International School Hanoi",
		nameKo: "하노이 콩코디아 국제학교",
		desc: "미국식 커리큘럼의 기독교 기반 사립 국제학교 입니다. 유아부터 Grade 12까지 운영하며, 미국 대학진학 준비형 교육과정을 강점으로 내세웁니다. ",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2011년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "하노이",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제/커리큘럼",
		item_tit_desc_4: "미국교육과정 AP / SAT",
		item_tit_5: "재학생수",
		item_tit_desc_5: "555명 이상",
		item_tit_6: "평균학비",
		item_tit_desc_6: "연간 VND 516,698,000~961,871,000 ※ 학년 및 프로그램에 따라 변동",
	},
};