export const univData2 = { // 말레이시아 국제학교
	'2_1': {
		nameEn: "Garden International School",
		nameKo: "가든 국제학교",
		desc: "70년 넘는 전통과 역사를 가진 명성 높은 영국학제 학교로 몽키아라내 위치 도보통학이 가능합니다. 정원수가 많은만큼 200여개 다양한 방과후 활동을 제공하고 있으며,입학난이도가 매우높고 대기자가 많은 학교입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1951년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "몽키아라",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 2천명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 4,000만원, 3,000~4,500만원",
	},
	'2_2': {
		nameEn: "Mont'kiara International School",
		nameKo: "MKIS 국제학교",
		desc: "미국식 학제의 IB학교, 외국인재학생 비율 높음, 몽키아라내 위치 도보통학 가능한 학교입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1994년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "몽키아라",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-12학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "미국식 Full IB (PYP/MYP/IBDP)",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 700명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 4,300만원 (3,200~4,800만원)",
	},
	'2_3': {
		nameEn: "International School of Kuala Lumpur",
		nameKo: "ISKL 국제학교",
		desc: "말레이시아에서 처음 설립된 미국식 명문국제학교, 학교규모가 크고 주재원 자녀가 많이 다니며 시설이 훌륭한 국제학교입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1965년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "암팡",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-12학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "미국식 AP / IBDP",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 2천명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 4,700만원 (3,500~5,400만원)",
	},
	'2_4': {
		nameEn: "The Alice Smith School",
		nameKo: "앨리스스미스 국제학교",
		desc: "말레이시아 최초의 비영리재단으로 2개의 캠퍼스로 나눠져 있습니다. 높은 외국인학생비율, 우수한 입시결과 및 다양한 스포츠 활동등으로 인기가 많은 국제학교입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1946년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "KL(초등) / 스리끔방안(중고등)",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 800명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 3,800만원 (2,600~4,500만원)",
	},
	'2_5': {
		nameEn: "The British International School Kuala Lumpur",
		nameKo: "BSKL 국제학교",
		desc: "글로벌 교육재단 Nord Anglia education 재단 소속, 도심에 위치하지만 규모가 크고 시설이 좋은 캠퍼스를 자랑. 원어민 비율이 높고 외국인 재학생 비율이 높은 학교입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2009년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "반다우타마",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 1,400명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 3,900만원 (2,600~4,640만원)",
	},
	'2_6': {
		nameEn: "IGB International School",
		nameKo: "IGB 국제학교",
		desc: "말레이시아에서 소수의 Full IB 교육을 하고 있는 국제학교입니다. 국제 경기용 사이즈 수영장과 육상 트랙, 극장, 예술 센터와 같이 학생들이 다양한 활동을 할 수 있도록 여러 우수한 시설을 갖추고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2014년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "숭가이블루",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-12학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "Full IB (PYP/MYP/IBDP)",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 500명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 3,500만원 (3,000~4,300만원)",
	},
	'2_7': {
		nameEn: "St. Joseph's International School",
		nameKo: "세인트조셉 국제학교",
		desc: "천주교계열의 학교로 도심권에 위치하고 있습니다. 싱가폴수학, 중국어수업비율이 높은 것이 특징인 학교입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2016년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "다만사라",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 1,000명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 2,900만원 (2,100~3,720만원)",
	},
	'2_8': {
		nameEn: "The International School @ Parkcity",
		nameKo: "ISP 국제학교",
		desc: "KL도심의 데사파크 지역안에 위치, 통학환경과 거주환경이 매우 좋기에 인기가 높습니다. 다양한 국적의 외국인 학생비율이 높고, 다양한 재능과 특기를 위한 수업제공이 많다는 것이 특징입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2011년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "데사파크시티",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 1,000명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 2,600만원 (900~3,100만원)",
	},
	'2_9': {
		nameEn: "Epsom College in Malaysia",
		nameKo: "엡솜 국제학교",
		desc: "영국 엡솜 컬리지의 자매학교. 보딩 학교 중 가장 기숙사 시스템을 잘 갖추고 있는 학교입니다. 높은 원어민 비율, 우수한 입시 결과 그리고 6만평 넘는 규모에 다양한 체육 시설을 갖추고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2014년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "느그리 슴발란",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 600명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "있음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 3,700만원 (2,000~4,130만원)",
	},
	'2_10': {
		nameEn: "Nexus International School",
		nameKo: "넥서스 국제학교",
		desc: "테일러스교육재단 소속의 영국식명문학교, 기숙사보유, 영국식교육을 진행하지만 12-13학년에는 IBDP를 한다는 차별점이 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2008년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "푸트라자야",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, IBDP",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 730명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "있음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 3,300만원 (1,700~3,970만원)",
	},
	'2_11': {
		nameEn: "KOLEJ TUANKU JA'AFAR",
		nameKo: "KTJ 국제학교",
		desc: "역사와 전통이 깊은 영국식 보딩학교로 7학년부터 기숙사 이용 가능한 학교이며 대부분 기숙사 생활을 하는 학교입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1991년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "느그리 슴빌란",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 700명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "있음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 2,900만원 (1,480~4,060만원)",
	},
	'2_12': {
		nameEn: "King Henry VII College",
		nameKo: "킹헨리 국제학교",
		desc: "영국 Christ college brecon 자매 국제학교로서 영국시스템을 운영하고 있고 원어민 교사비율이 높은 국제학교입니다. 기숙사 가능하며, 사이버자야 신도시에 위치하고 있어 주변 환경이 안전하고 깨끗합니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2018년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "사이버자야",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 600명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "있음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 2,800만원 (900~3,650만원)",
	},
	'2_13': {
		nameEn: "Fairview International School",
		nameKo: "페어뷰 국제학교",
		desc: "말레이시아에서 IB인증을 최초로 인증받은곳으로 IB교사 육성하는 프로그램을 지니고 있음. 경제적인 학비의 Full IB 국제학교입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1978년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "왕사마주",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-12학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "Full IB (PYP/MYP/IBDP)",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 600명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "있음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 2,000만원 (1,064~2,470만원)",
	},
	'2_14': {
		nameEn: "Sunway International School",
		nameKo: "선웨이 국제학교",
		desc: "썬웨이 그룹소속, 캐나다 학제 또는 영국학제 중 선택이 가능하며 다양한 입시커리큘럼, 캠퍼스 시설 넓고 좋으며 위치 입지조건 좋음, 썬웨이 대학교 옆에 위치하고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2008년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "수방자야",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-12학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "캐나다 온타리오 / 영국 캠브리지",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 1,000명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "있음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 2,600만원 (2,090~3,040만원)",
	},
	'2_15': {
		nameEn: "Oasis International School",
		nameKo: "오아시스 국제학교",
		desc: "오랜역사의 미국식 교육을 하는 오아시스교육재단에 소속된 학교로 한국 용산국제학교와 자매학교입니다. 모든교사가 미국교육 자격증을 소지하고 있으며, 다양한 방과후 활동을 제공하고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2018년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "림바유",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-12학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "미국교육과정 AP / SAT",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 350명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 2,300만원 (2,000~3,135만원)",
	},
	'2_16': {
		nameEn: "Australian International School Malaysia",
		nameKo: "AISM 국제학교",
		desc: "말레이시아 테일러스교육그룹에서 운영하며 가장 오래된 호주식 국제학교입니다. 친환경적인 캠퍼스, 다양한 액티비티 등의 수업을 제공하고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2000년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "스리끔방안",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-12학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "호주 뉴사우스웨일주",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 400명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 3,100만원 (2,200~3,700만원)",
	},
	'2_17': {
		nameEn: "Peninsula International School Australia",
		nameKo: "PISA 국제학교",
		desc: "말레이시아에서 호주의 빅토리아 주 교육과정을 제공하는 국제학교로 VCE졸업장을 받게 됩니다. 기숙사를 제공하며 영어가 부족한 학생을 위한 집중반과정이 잘되어있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2018년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "세티아알람",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-12학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "호주 VCE",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 400명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "있음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 2,100만원 (1,300~2,850만원)",
	},
	'2_18': {
		nameEn: "Help International School",
		nameKo: "헬프 국제학교",
		desc: "도심권에 위치한 영국식 교육을 제공하면서 경제적인 학비, STEM교육 중시, 우수한 학업성적을 특징으로하는 국제학교입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2014년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "샤알람",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 1,400명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,930만원 (1,490~2,900만원)",
	},
	'2_19': {
		nameEn: "Sri KDU International School Kota Damansara",
		nameKo: "Sri KDU 국제학교 (코타 다만사라 캠퍼스)",
		desc: "XCL교육재단에서 운영하는 영국식 교육과정 국제학교, 학업과 가치 중심의 교육을 제공하며, 스포츠, 음악, 공연 예술, 지역사회 봉사 활동 등을 통해 학생들의 전인적 성장을 추구합니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2011년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "코타다만사라",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-11학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 1,000명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 2,240만원 (1,500~2,920만원)",
	},
	'2_20': {
		nameEn: "Sri KDU International School Subang Jaya",
		nameKo: "Sri KDU 국제학교 (수방 캠퍼스)",
		desc: "XCL교육재단에서 운영하는 영국식 교육과정 국제학교, 수방자야 캠퍼스는 전학년 과정이 있으며 주변에서 도보로 통학할 수 있는 환경이 특징, 영어보충레벨이 4단계로 되어있음.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2017년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "수방자야",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 700명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "있음(외부, 10학년이상)",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,860만원 (1,400~2,280만원)",
	},
	'2_21': {
		nameEn: "Tenby Schools Setia Eco Park",
		nameKo: "텐비 국제학교 (세티아에코 파크 캠퍼스)",
		desc: "2018년 ISP에 가입한 텐비 중에서 A레벨까지 제공하고 가장 유명하고 오래된 캠퍼스, 적절한 학비에 13학년까지 있는 체계적인 교육시스템을 갖추고 있으면서 방대한 캠퍼스 시설을 갖추고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2008년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "세티아알람",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 2,000명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,900만원 (990~2,730만원)",
	},
	'2_22': {
		nameEn: "Tenby Schools Setia Eco Hill",
		nameKo: "텐비 국제학교 (세티아에코 힐 캠퍼스)",
		desc: "자연친화적인 환경, 100여가지 방과후가 있고 한국인 학생 수가 많지 않은것이 특징, 가성비가 우수한 국제학교로 텐비 중에서 가장 학비 저렴하고 시설 좋음.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2016년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "세메니(Semenyih)",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 800명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,550만원 (800~1,885만원)",
	},
	'2_23': {
		nameEn: "Tenby Schools Tropicana Aman",
		nameKo: "텐비 국제학교 (트로피카나 아만 캠퍼스)",
		desc: "텐비 교육재단 캠퍼스로 가성비가 좋음, 매우 넓고 큰 대규모의 학교로 최신식 시설, 친환경의 캠퍼스로서 여러가지 다양한 활동을 할 수 있도록 최적의 교육환경을 제공해 주고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2018년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "Kota Kemuning",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-11학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 500명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,820만원 (990~2,570만원)",
	},
	'2_24': {
		nameEn: "Taylor's International School Kuala Lumpur",
		nameKo: "테일러스 국제학교 (KL 캠퍼스)",
		desc: "테일러스 대학이 속해있는 테일러스 명문사학 재단에서 운영하고 있기 때문에 탄탄한 교육프로그램을 가지고 있습니다. 영국계이지만 1월에 시작하며 도심권에 위치하고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2014년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "말루리 (Maluri)",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-11학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 1,200명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,530만원 (975~2,030만원)",
	},
	'2_25': {
		nameEn: "Taylor's International School Puchong",
		nameKo: "테일러스 국제학교 (푸총 캠퍼스)",
		desc: "테일러스 재단소속의 학교로 시설이 매우 좋고 다양한 ECA 프로그램이 있습니다. 테일러스 암팡보다는 외곽지역에 있지만 좀 더 활동적인 프로그램과 넓은 캠퍼스의 장점을 지니고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2015년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "푸총",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-11학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 1,300명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,530만원 (975~2,030만원)",
	},
	'2_26': {
		nameEn: "UCSI International School Kuala Lumpur",
		nameKo: "UCSI 국제학교 (KL 캠퍼스)",
		desc: "UCSI그룹이 운영하는 학교로 핀란드 교육 모델을 도입하여 전인적 교육을 지향하며, 혁신적인 기술 교육을 강조하면서 학생들에게 코딩, 로봇 공학, IT 기술 등을 가르칩니다. 도심권에 위치 입지조건이 좋고 학비대비 원어민교사 비율이 높은 학교입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2021년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "체라스",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-11학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 450명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "있음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,540만원 (1,255~1,785만원)",
	},
	'2_27': {
		nameEn: "UCSI International School, Subang Jaya",
		nameKo: "UCSI 국제학교 (수방 캠퍼스)",
		desc: "UCSI그룹이 운영하는 학교로 영국 커리큘럼의 학교로 IGCSE교육까지 제공합니다. 인프라 환경이 좋은 지역에 위치하고 있으면서 비교적 저렴한 학비로 우수한 교육을 제공하면서 성적이 우수한 학교입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2013년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "수방",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-11학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 350명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 970만원 (1,254~1,785만원)",
	},
	'2_28': {
		nameEn: "UCSI International School Springhill",
		nameKo: "UCSI 국제학교 (스프링힐 캠퍼스)",
		desc: "말레이시아에서 국제 바칼로레아(IB) 프로그램을 제공하는 몇 안 되는 학교 중 하나로, 전일제 및 기숙사 교육을 제공합니다. 넓은 캠퍼스에 최신식의 다양한 시설을 훌륭하게 갖추고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2012년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "포트딕슨",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-12학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "Full IB (PYP/MYP/IBDP)",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 100명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "있음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,200만원 (783~1,415만원)",
	},
	'2_29': {
		nameEn: "Maple Leaf Kingsley International School",
		nameKo: "킹슬리 국제학교",
		desc: "영국식 교육을 제공하면서 2만평 규모의 넓은 캠퍼스와 시설을 갖춘 학교입니다. 펜싱, 승마 등을 배울 수 있고 방과후 과목이 많이 있는 것이 특징, 합리적인 학비에 A레벨입시까지 하고, 보딩시설을 갖추고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2011년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "수방자야 푸트라하이츠",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 1,400명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "있음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,100만원 (860~1,385만원)",
	},
	'2_30': {
		nameEn: "Adcote Matrix International School",
		nameKo: "에드코트 매트릭스 국제학교",
		desc: "영국식 커리큘럼을 제공하고 있으며 명문 기숙사 학교인 Adcote와 콜라보를 하여 운영, 2만 4천여평의 캠퍼스에 다양한 시설을 갖추고 있습니다. 저렴한 학비 및 기숙사 비용, 우수한 진학 성적을 보이고 있는 학교입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2014년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "느그리슴발란",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 600명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "있음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,700만원 (990~2,000만원)",
	},
	'2_31': {
		nameEn: "Sri Bestari International School",
		nameKo: "스리베스타리 국제학교",
		desc: "사립학교에서부터 시작되었으며 2017년부터 영국커리큘럼을 기반으로 한 수업을 시작하였고, 2020년 새로운 캠퍼스를 건축 현재 위치에서 국제학교로서 시작하였습니다. 경제적인 교육비로 도심권에 위치하고 있고 큰 규모의 다양한 시설을 고루 잘 갖추고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2020년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "반다르 스리 다만사라",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-11학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 700명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,100만원 (780~1,415만원)",
	},
	'2_32': {
		nameEn: "Straits International School Rawang",
		nameKo: "스트레이트 라왕 국제학교",
		desc: "ISP 교육 재단 소속으로 2018년도에 설립, 최신식으로 넓은 학교시설을 갖추고 있습니다. 합리적인 교육비, 단계별 영어보충반 프로그램을 운영하고 있으며 위치는 다소 도시외곽지역에 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2018년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "라왕",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-11학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 550명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,360만원 (960~1,900만원)",
	},
	'2_33': {
		nameEn: "Eaton International School, Kajang",
		nameKo: "이튼 국제학교 (카장 캠퍼스)",
		desc: "영국식 교육프로그램 제공, 현대적인 시설과 친환경 캠퍼스를 갖추고 있습니다. IGCSE과정까지 제공하면서 STEAM교육에 중점을 두면서 학비대비 원어민교사비율이 높은 학교입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2013년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "카장 Kajang Jade Hills",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-11학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 700명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,550만원 (1,240~1,910만원)",
	},
	'2_34': {
		nameEn: "Eaton International School, Sahalam",
		nameKo: "이튼 국제학교 (샤알람 캠퍼스)",
		desc: "개교한지 얼마 안 된 새로운 캠퍼스라 깨끗하고 첨단 시설의 캠퍼스가 특징입니다. 공원 주변의 아름다운 자연과 함께 캠퍼스 생활을 할 수 있고, 높은 원어민 교사 비율이 특징입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2024년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "샤알람",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-11학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 100명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,500만원 (1,240~1,910만원)",
	},
	'2_35': {
		nameEn: "Sayfol International School",
		nameKo: "세이폴 국제학교",
		desc: "영국식커리큘럼의 학교로 학비가 매우 합리적인 학교입니다. 쿠알라룸푸르 중심부에 위치해서 접근성이 좋으며, 다양한 문화와 글로벌 환경을 제공하고 있으며, 가장 오래된 국제학교이기에 학교시설은 다소 연식이 있는 편입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "1985년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "암팡",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 1,800명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,000만원 (715~1,370만원)",
	},
	'2_36': {
		nameEn: "Asia Pacific International School",
		nameKo: "아시아퍼시픽 국제학교",
		desc: "ISP 재단 소속의 학교입니다. ISP는 45개 이상의 학교를 전세계에 가지고 있는 재단으로서, 말레이시아의 명문 사립 대학교인 APU가 소속이 되어있습니다. 시설이 매우 훌륭하고 한국학생비율이 높지 않습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2013년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "셀랑고르 수방",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-11학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 500명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,580만원 (950~2,150만원)",
	},
	'2_37': {
		nameEn: "Rocklin International School",
		nameKo: "락클린 국제학교",
		desc: "미국식 교육프로그램을 제공함. 학비 가성비가 있으면서 도심권에 위치해서 인프라가 좋은 환경. 캠퍼스가 크게 갖춰지지는 않았고 건물내에 위치하고 있습니다. AP/SAT과정을 제공하면서 미국계 커리큘럼을 희망할 시 선택할 수 있는 학교입니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2020년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "체라스",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-12학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "미국교육과정 AP / SAT",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 200명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "없음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 1,600만원 (1,500~1,750만원)",
	},
	'2_38': {
		nameEn: "Charterhouse International Secondary School",
		nameKo: "차터하우스 국제학교",
		desc: "역사가 깊은 사립학교로, 세컨더리 학생 대상으로 운영하고 있습니다. IGCSE와 A레벨로 이어지는 영국제 입시 특화해서 교육하는 학교로 입시성적도 우수합니다. 모든 시설은 건물내에있고 기숙사를 제공합니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2021년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "스리 하타마스",
		item_tit_3: "학년구성",
		item_tit_desc_3: "9-12학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 130명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "있음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 4,140만원",
	},
	'2_39': {
		nameEn: "Concord College International School Malaysia",
		nameKo: "콩코드 국제학교",
		desc: "영국의 명문 학교 Concord College UK의 전통과 교육 철학을 이어받고 있으면서 운영노하우를 그대로 반영하고 있는 학교입니다. 방대한 캠퍼스에 우수한 신축시설을 갖추고 있으며 기숙사도 제공하고 있습니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2024년",
		item_tit_2: "학교위치",
		item_tit_desc_2: "셀랑고르 세팡",
		item_tit_3: "학년구성",
		item_tit_desc_3: "유치원-13학년",
		item_tit_4: "학제 / 커리큘럼",
		item_tit_desc_4: "영국식 IGCSE, A-LEVEL",
		item_tit_5: "학생수",
		item_tit_desc_5: "약 250명",
		item_tit_6: "기숙사여부",
		item_tit_desc_6: "있음",
		item_tit_7: "평균학비",
		item_tit_desc_7: "연간 3,150만원 (2,015~3,915만원)",
	},
};