export const univData3 = { // 송도 대학
	'3_1': {
		nameEn: "SUNY Korea (State University of New York)",
		nameKo: "뉴욕주립대 계열",
		desc: "SUNY Korea는 2012년에 설립된 송도 IGC의 미국 대학 캠퍼스입니다. 미국 본교와 동일한 커리큘럼과 학위를 제공하며, 공학·컴퓨터·경영 분야에서 실무 중심 교육과 글로벌 취업 경쟁력을 갖춘 인재 양성을 목표로 합니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2012년",
		item_tit_2: "재학생수",
		item_tit_desc_2: "1,000명 이상",
		item_tit_3: "대학 인지도",
		item_tit_desc_3: "전미 58위",
		item_tit_4: "대표전공",
		item_tit_desc_4: "컴퓨터공학, 기계공학, 경영, 전기전자",
		item_tit_5: "평균학비",
		item_tit_desc_5: "연간 약 USD 20,000 ~ 25,000 (전공 및 장학금 여부에 따라 상이)",
		note: "* 입학조건 : 고3 내신성적 4등급 이내를 요구하고, 영어공인성적 및 자기소개서·추천서 등의 추가서류를 요청할 수 있습니다."
	},
	'3_2': {
		nameEn: "University of Utah Asia Campus",
		nameKo: "유타대학",
		desc: "유타대학교 아시아캠퍼스는 송도 IGC에서 운영되는 미국 공립 연구중심대학의 해외 캠퍼스입니다. 미국 본교와 동일한 커리큘럼과 학위를 제공하며, 일부 전공은 본교 캠퍼스에서 수학할 기회도 제공됩니다. 커뮤니케이션, 심리학, 게임 등 실무 중심 전공을 통해 글로벌 인재 양성을 목표로 합니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2014년",
		item_tit_2: "재학생수",
		item_tit_desc_2: "공식 전체 재학생수 미공개",
		item_tit_3: "대학 인지도",
		item_tit_desc_3: "전미 100~120위",
		item_tit_4: "대표전공",
		item_tit_desc_4: "커뮤니케이션, 심리학, 게임, 경영 등",
		item_tit_5: "평균학비",
		item_tit_desc_5: "연간 약 USD 20,000 ~ 22,000 (전공 및 장학금 여부에 따라 상이)",
		note: "* 입학조건 : 고3 내신성적 5등급 이내를 요구하고, 영어공인성적 및 자기소개서 준비가 필요합니다. "
	},
	'3_3': {
		nameEn: "Ghent University Global Campus",
		nameKo: "겐트대학교",
		desc: "겐트대학교 글로벌캠퍼스는 2014년 송도 IGC에 설립된 유럽 연구중심대학의 해외 캠퍼스입니다. 벨기에 본교와 동일한 교육과정과 학위를 제공하며, 전 과정이 영어로 진행되는 연구 중심 커리큘럼이 특징입니다. 특히 생명과학, 바이오, 환경공학 분야에서 강점을 가지며 글로벌 연구 인재 양성을 목표로 합니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2014년",
		item_tit_2: "재학생수",
		item_tit_desc_2: "1,000명 이상 ",
		item_tit_3: "대학 인지도",
		item_tit_desc_3: "전세계 150~200위",
		item_tit_4: "대표전공",
		item_tit_desc_4: "생명공학, 환경공학, 식품공학",
		item_tit_5: "평균학비",
		item_tit_desc_5: "연간 약 USD 13,000 ~ 15,000 (전공 및 장학금 여부에 따라 상이)",
		note: "* 입학조건 : 고3 내신성적 5등급 이내를 요구하고, 영어공인성적 및 자기소개서 준비가 필요합니다. "
	},
	'3_4': {
		nameEn: "George Mason University Korea",
		nameKo: "조지메이슨대학",
		desc: "George Mason University Korea는 송도 IGC에 위치한 미국 공립 연구중심대학의 해외 캠퍼스입니다. 미국 본교와 동일한 커리큘럼과 학위를 제공하며, 정책, 경제, 경영, 국제관계 등 사회과학 분야 중심의 교육을 통해 글로벌 인재 양성을 목표로 합니다.",
		item_tit_1: "설립년도",
		item_tit_desc_1: "2014년",
		item_tit_2: "재학생수",
		item_tit_desc_2: "1,000명 이상 ",
		item_tit_3: "대학 인지도",
		item_tit_desc_3: "전미 100~120위",
		item_tit_4: "대표전공",
		item_tit_desc_4: "경제, 경영, 국제관계",
		item_tit_5: "평균학비",
		item_tit_desc_5: "연간 약 USD 20,000  ~ 23,000 (전공 및 장학금 여부에 따라 상이)",
		note: "* 입학조건 : 고3 내신성적 5등급 이내를 요구하고, 영어공인성적 및 자기소개서 준비가 필요합니다. "
	}
};